# Generated by Django 5.0.1 on 2025-11-17 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name for the list', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead List',
                'verbose_name_plural': 'Lead Lists',
                'db_table': 'lead_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('current_title', models.CharField(db_index=True, max_length=255)),
                ('current_company', models.CharField(db_index=True, max_length=255)),
                ('company_linkedin_url', models.URLField(blank=True, max_length=500)),
                ('headline', models.TextField(blank=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=255)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('seniority_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'VP'), ('c_level', 'C-Level'), ('owner', 'Owner'), ('partner', 'Partner')], db_index=True, max_length=20)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('bio', models.TextField(blank=True)),
                ('external_id', models.CharField(db_index=True, help_text='Unique identifier from LinkedIn API', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='leads_first_n_6baaef_idx'), models.Index(fields=['current_company'], name='leads_current_028914_idx'), models.Index(fields=['country', 'location'], name='leads_country_0e5fa8_idx'), models.Index(fields=['industry'], name='leads_industr_edc26b_idx'), models.Index(fields=['seniority_level'], name='leads_seniori_f7549b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this lead in this list')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='leads.lead')),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='leads.leadlist')),
            ],
            options={
                'verbose_name': 'Lead List Item',
                'verbose_name_plural': 'Lead List Items',
                'db_table': 'lead_list_items',
                'ordering': ['-added_at'],
                'unique_together': {('lead', 'lead_list')},
            },
        ),
    ]
