# Generated by Django 5.0.1 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_remove_lead_leads_current_028914_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_company_title_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_industry_seniority_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="leadlistitem",
            name="lead_list_item_idx",
        ),
        migrations.RemoveIndex(
            model_name="leadlistitem",
            name="lead_list_item_added_idx",
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="seniority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("specialist", "Specialist"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                    ("head", "Head"),
                    ("vp", "VP"),
                    ("c_level", "C-Level"),
                    ("owner", "Owner"),
                    ("partner", "Partner"),
                    ("intern", "Intern"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leadlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="leadlistitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["current_company"], name="leads_current_028914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["industry"], name="leads_industr_edc26b_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["seniority_level"], name="leads_seniori_f7549b_idx"
            ),
        ),
    ]
